### ISSUE TITLE
Number of negative examples and pace of learning

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#111]
As a preparation to implementing GloVe, I am trying to understand this:
https://papers.nips.cc/paper/5477-neural-word-embedding-as-implicit-matrix-factorization.pdf

Essentially, it says that the skip gram algorithm is equivalent to a matrix factorization algorithm (which is what GloVe is).

This is a really nice blog entry about this topic:

https://medium.com/radix-ai-blog/unifying-word-embeddings-and-matrix-factorization-part-2-a0174ace78b8

But one of the things the blog entry discusses is that the number of negative entries can have an effect on the speed by which the algorithm learns. This means that maybe we can speed up the learning by increasing the number of negative entries with some reduction in the number of iterations (it is hard to know exactly what the final effect would be). In any case, we should definitely test the effect on the speed of convergence and also final accuracy of changing the number of negative examples -- let's done a few runs with k=16, 32, 64, 128, 256, 512 for example.

**Comment by justaddcoffee** [comment]
Interesting, thanks Peter for the digging! 

Related - it'll be awesome if/when we can use @LucaCappelletti94 's code to automagically tune our hyperparameters

**Comment by pnrobinson** [comment]
Given our overall good performance, I do not think that it is necessary to do more optimization of the number of neg examples.
