### ISSUE TITLE
Short sentences

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#113]
Using this
```
tensor_data,  count_list, dictionary,  reverse_dictionary = encoder.build_dataset()
```
with one of my all time fav books, Treasure Island (I really need to re-read this again!), I am getting some sentences that are too short. 
```
<tf.RaggedTensor [[47, 38, 650, 69, 40, 1351, 1145, 1352], [], [650, 353, 495, 2209, 989], [155, 2210, 2211, 62, 496, 120, 84], [353, 226, 47, 38, 402, 1353], [650, 1354, 990, 38, 497], [], [], .....
```
We should figure out how we want to handle things like this. I am guessing that for many purposes, people will just take the entire book as a string, but we need to define an expected behavior. Thoughts?

**Comment by LucaCappelletti94** [comment]
Closing this issue as deprecated in the new version of Embiggen. Please feel free to reopen as need be.
