### ISSUE TITLE
calculate_vocabulary_size

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#114]
in calculate_vocabulary_size, we have:
```
def calculate_vocabulary_size(self) -> None:
 if any(isinstance(el, list) for el in self.data):
            (...)
        else:
            self.vocabulary_size = min(self.max_vocabulary_size, len(set(self.data)) + 1)
            print('Vocabulary size (flat) is {vocab_size}'.format(vocab_size=self.vocabulary_size))
```
but by the time we get here, we also have a self.dictionary and can avoid doing the len(set(list(x))) trick. I am guessing that even with the graph, we will also pass the dictionary/reverse_dictionary woth node names, right? So we can just go
```
    self.vocabulary_size = min(self.max_vocabulary_size, len(self.dictionary)) )
```
I think that we also do not need the +1 here.
Please shout if this is wrong.

**Comment by vidarmehr** [comment]
@pnrobinson 

Hi Peter,
You changed the above code to this:

`def calculate_vocabulary_size(self) -> None:`
`if self.word2id is None and self.vocabulary_size == 0:`
                                       `self.vocabulary_size = 0`
`elif self.vocabulary_size ==0:`
                      `            self.vocabulary_size = len(self.word2id)`
`return None`

Can I close this issue?

**Comment by pnrobinson** [comment]
Thanks, I think we might want to refactor this bit of code, it is not elegant.
Currently the constructor allows the user to pass vocal_size, but I think we probably do not want to allow this. If the user wants to limit vocabulary size they need to do so with the text_encoder class. 
So my vote would be to remove the vocal_size parameter from the constructor and to simplify this code

**Comment by vidarmehr** [comment]
I work on this after making sure that the vocabulary_size is calculated correctly.

**Comment by pnrobinson** [comment]
We have refactored such that the vocab size needs to be calculated outside of the Word2vec/GloVe classes.
