### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#121]
"N2V" is not the world's most original name.
What do we think about 
```
Vertex and Vocabulary for Embedding (V24E)
Vertex and Vocabulary Embedding for Machine Learning (V2EML)
Vertex and Word emBEEDDing LEarner (VW-Beeddle) 
```
Any other ideas?

**Comment by callahantiff** [comment]
I love these! Other thoughts building on what you already added:
- V2V4ML
- V4ML - just collapsing the V2V4ML

Will keep thinking...

**Comment by justaddcoffee** [comment]
These are all good. Another one we considered at one point I think was star2vec (sort of captures the effort to implement lots of different algorithms)

**Comment by pnrobinson** [comment]
``TV4ML`` (pronounced "TV for ML", i.e., two V's (vertices and vocabularies) for machine learning?

**Comment by vidarmehr** [comment]
I think we should keep "E" for embedding somewhere in the name.  Maybe VE4ML (Vertex embedding for machine learning)?

**Comment by deepakunni3** [comment]
@vidarmehr I like your suggestion.
Its also an easy name to say: VE4ML (we formal)

**Comment by pnrobinson** [comment]
Can we get an 'ry' into there somehow

VERe4ML ?

Vertex Embedded Representation for Machine Learning

i.e., "very formal"?

**Comment by vidarmehr** [comment]
> @vidarmehr I like your suggestion.
> Its also an easy name to say: VE4ML (we formal)

Thanks! I did not think that it can be read as "we formal" :)

**Comment by callahantiff** [comment]
G4ML --> Graph4ML

**Comment by justaddcoffee** [comment]
Embiggen!

**Comment by callahantiff** [comment]
GREML
GREL

**Comment by pnrobinson** [comment]
What was our final decision here? I am going to go with GREML for now, but if anybody would like to plead for another name we can discuss!

**Comment by pnrobinson** [comment]
Actually, maybe embiggen is better since people might want to use just the word2vec part of the package?

**Comment by realmarcin** [comment]
My only reservation would be that there are now many more advanced word2vec
flavors with various grammar, language document models -- so word2vec
itself might not be a huge sell?

**Comment by vidarmehr** [comment]
Shall we vote for the names? I think GREML and embiggen are final candidates.

**Comment by pnrobinson** [comment]
EMBigGEB

**Comment by pnrobinson** [comment]
GREML

**Comment by vidarmehr** [comment]
> EMBigGEB

Thanks, Peter. What does it stand for? Embedding Generator ...? Can we delete  "g" or "G" in the middle of the word?

**Comment by pnrobinson** [comment]
@deepakunni3 @justaddcoffee @cmungall @vidarmehr @callahantiff @LucaCappelletti94 
-- any other votes for the name?
-- Is there any other Python package called embiggen?

**Comment by justaddcoffee** [comment]
Both contenders are good, I guess I'll vote for embiggen

> Is there any other Python package called embiggen?

Turns out there is a package for this! Both names are free, according to `is-taken`: 

```
(venv) ~/PycharmProjects/ *master $ pip install is-taken
(venv) ~/PycharmProjects/ *master $ is-taken embiggen
embiggen is free to use
(venv) ~/PycharmProjects/ *master $ is-taken GREML
GREML is free to use
```

**Comment by LucaCappelletti94** [comment]
Since the [definition that I found online of the word](https://www.merriam-webster.com/dictionary/embiggen) is: 

> Definition of embiggen
>transitive verb
>informal + humorous
>: to make bigger or more expansive : ENLARGE, EXPAND
>This incredible chart was the final product. (Click to embiggen.)
>— Erik Malinowski
>There are many painters who rely on computers as a tool or arbitrary gimmick, but the recent >striated abstract paintings of Linda Day translate digital structures into painting language in a >seamless way that embiggens both.
>— Doug Harvey

I would vote for this one as well.

**Comment by vidarmehr** [comment]
So, we have 4 votes (Peter, Justin, Vida, Luca) for embiggen.
@callahantiff @deepakunni3 @realmarcin @cmungall 
Any vote for GREML?

**Comment by pnrobinson** [comment]
Can we also vote on documentation? What about readthedocs? I seem to recall that we can automatically generate some documentation from the Pydoc? Then we just need to add some tutorials, right?

**Comment by callahantiff** [comment]
> So, we have 4 votes (Peter, Justin, Vida, Luca) for embiggen.
> @callahantiff @deepakunni3 @realmarcin @cmungall
> Any vote for GREML?

My vote is for GREML 😄

**Comment by deepakunni3** [comment]
I vote for GREML, but there might be a confusion with the name since GREML exists in genomics.
https://www.rdocumentation.org/packages/qgg/versions/1.0.3/topics/greml
https://www.pnas.org/content/113/32/E4579

I do not see similar conflicts with embiggen.

**Comment by pnrobinson** [comment]
hmm, now we need a decision procedure!

**Comment by cmungall** [comment]
I like embiggen

note there is a GREMLIN already in the graph space

**Comment by realmarcin** [comment]
embiggen is Simpsons town motto, can't lose with that :)
It does sound a little like something our president might use, but that makes it even more timely :)

so, is it technically (capitalization)?
EmbigGen

what is the 'ig' ?

**Comment by pnrobinson** [comment]
I think the clear majority is for embiggen (note: I actually liked VeRe4ML but embiggen was close 2nd!). Let's go ahead and change the name of the repo  -- I will do so tomorrow if nobody shouts!

**Comment by vidarmehr** [comment]
We renamed the repo to embiggen. so, I close this issue.
