### ISSUE TITLE
setup.py issue for tensorflow (known issue -- to keep track)

### ISSUE THREAD

**Issue by realmarcin** [monarch-initiative/embiggen#123]
This is just to keep track that the current setup.py throws an error when trying to install tensorflow:

No local packages or working download links found for tensorflow>=2.0

The workaround is something like:
pip install --upgrade tensorflow

And actually in a cluster environment you will usually want something like:
module load ml/tensorflow/2.1.0-py37

**Comment by pnrobinson** [comment]
This seems to be working now, at least in virtual env's. Can we close or if the issue persists should we just add this to the README? @realmarcin

**Comment by LucaCappelletti94** [comment]
Closing this issue as deprecated in the new version of Embiggen. Please feel free to reopen as need be.
