### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#137]
What actually is the best way of publishing a website with documentation about how to use this software? In general, Python documentation seems to be automagically generated by autosphinx? Can we combine that with readthedocs?

**Comment by deepakunni3** [comment]
@pnrobinson Yes, this is definitely the best way to go.

The automatic docs can be hosted in ReadTheDocs and well as GitHub pages, depending on what we want to use.

I can take a shot at this

**Comment by pnrobinson** [comment]
@deepakunni3 That would be great. I am fine with either option, whatever is easiest to set up!

**Comment by pnrobinson** [comment]
Here is a link to the new readthedocs site:
https://embiggen.readthedocs.io/en/latest/index.html
It still needs work but I am closing this issue and we can make specific issues for specific documentation pages
