### ISSUE TITLE
update runAnalysis and runSkipGram_ppi

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/embiggen#138]
update runAnalysis.py and runSkipGram_ppi.py according to new changes

**Comment by vidarmehr** [comment]
@pnrobinson Do you think we should still keep these tow files? These are codes to test embedding and link prediction. The runLinkPrediction_ppi already embeds the small training ppi file and predict links from pos/neg edges.

**Comment by pnrobinson** [comment]
I would suggest we want to keep one example file for running the package (just one file!)

**Comment by vidarmehr** [comment]
@pnrobinson  I extracted pos/neg train/valid/test sets from the karate edge list and created a new branch called analysis in which runLinkPreiction_karate.py runs embedding and link prediction on the edge lists.
runSkipGram only embeds a graph and runAnalysis has to be modified to be used as the embedding and link prediction code. 
So, if it is ok with you, I will just keep runLinkPrediction_karate.py.

**Comment by vidarmehr** [comment]
@pnrobinson I have deleted runSkipGram_ppi. After your approval on pull request, I will only keep runAnalysis.

**Comment by vidarmehr** [comment]
I deleted runLinkPrediction_karate.py. It is already included in runAnalysis.py. So, I close this issue.
