### ISSUE TITLE
Local install does not work

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#166]
Hi everybody, we probably need to start testing how embiggen will work for others. I just tried this
```
python setup.py install --user

```
However, when I try to import embiggen, I get this
```
>>> import embiggen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/lib/python3.7/site-packages/embiggen-0.6.0-py3.7.egg/embiggen/__init__.py", line 9, in <module>
    from .csf_graph import CSFGraph
ModuleNotFoundError: No module named 'embiggen.csf_graph'
```
If I go to the local installation, I see that only the top level files get used:
```
/.local/lib/python3.7/site-packages/embiggen-0.6.0-py3.7.egg/embiggen$ ls
coocurrence_encoder.py  link_prediction_functions.py  random_walk_generator.py
glove.py                link_prediction.py            text_encoder.py
hetnode2vec.py          neural_networks.py            __version__.py
__init__.py             __pycache__                   word2vec.py
```
So for whatever reason, the csf_graph file is not getting into the installation. 

Any ideas?

**Comment by pnrobinson** [comment]
PS, I was trying with this branch: https://github.com/monarch-initiative/embiggen/pull/165

**Comment by LucaCappelletti94** [comment]
I believe you should install the repository by using `pip install .`, instead of using the `setup.py`, as this can patch numerous errors that are not handled by the `setup.py` file, but I don't think that the error you have listed falls between those. I will look into this.

**Comment by justaddcoffee** [comment]
@pnrobinson can't reproduce this error

What steps did you do before `python setup.py install --user` - I guess you did a `git clone https://github.com/monarch-initiative/embiggen.git`?

**Comment by pnrobinson** [comment]
I did this after a git pull (develop)
```
$ pip install . --user
(...)
uccessfully built embiggen
Installing collected packages: embiggen
  Found existing installation: embiggen 0.6.0
    Uninstalling embiggen-0.6.0:
      Successfully uninstalled embiggen-0.6.0
Successfully installed embiggen-0.6.0
```
When I try to import it, I get this error (on a debian box)
```
>>> import embiggen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/lib/python3.7/site-packages/embiggen/__init__.py", line 9, in <module>
    from .csf_graph import CSFGraph
ModuleNotFoundError: No module named 'embiggen.csf_graph'
```

**Comment by pnrobinson** [comment]
In the meantime, everything is working!
