### ISSUE TITLE
Close resources properly

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#179]
/Users/peterrobinson/GIT/embiggen/embiggen/text_encoder.py:134: ResourceWarning: unclosed file 
...

/Users/peterrobinson/GIT/embiggen/embiggen/text_encoder.py:141: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/peterrobinson/GIT/embiggen/tests/data/greatExpectations3.txt' mode='r' encoding='UTF-8'>

**Comment by callahantiff** [comment]
@pnrobinson - I'm fixing this as we speak 😄
