### ISSUE TITLE
ModuleNotFoundError: No module named 'parameterized'

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#180]
I am getting errors from the unit tests because I cannot seem to get python to recognize parameterized
```
ModuleNotFoundError: No module named 'parameterized'
```
even though I install parameterized successfully in PyCharm

**Comment by LucaCappelletti94** [comment]
Hello @pnrobinson, I have run the tests on all the available branch and I cannot seem to be able to reproduce the error, would you consider having a short call afterwards to try and deal with this issue?

**Comment by pnrobinson** [comment]
I have not seen this error since then. I will close this issue for now!
