### ISSUE TITLE
write.embedding

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/embiggen#184]
@callahantiff @pnrobinson Luca and I are trying to refactor the embiggen in a way that we could use Ray optimization. Luca wants to know if we can skip  
write_embeddings(args.embed_graph, model.embedding, reverse_worddictionary)and instead of writing the embedding into a file and loading, we just load embedding in link prediction?

**Comment by callahantiff** [comment]
Seems reasonable to me, assuming there would still be a way to generate and write embeddings for people who don't intend to run link prediction. Will that still be possible?

**Comment by vidarmehr** [comment]
@callahantiff Thanks Tiffany. Yes. We will save the embeddings in a file, but in link prediction I don't think we need to read from the embeddings.

**Comment by pnrobinson** [comment]
Can we make an optional way of writing the embeddings? I am guessing that for most real use cases, people will want too save the embeddings in a file.

**Comment by LucaCappelletti94** [comment]
Hello! My proposal would be to create a method to save the embedding, optionally, when required to do so, but to avoid **having to** save the embedding for it to be used in the following step.

**Comment by LucaCappelletti94** [comment]
I have reimplemented [the transformation from RaggedTensor to dictionary](https://github.com/monarch-initiative/embiggen/blob/59362b3748aac1d4b4ed5190e482b9f9dea308fc/embiggen/word2vec.py#L123) and the [way we can save the embedding](https://github.com/monarch-initiative/embiggen/blob/59362b3748aac1d4b4ed5190e482b9f9dea308fc/embiggen/word2vec.py#L130). I believe that these methods are cleaner and straightforward.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Luca, thanks a lot! It looks great to me.  I am going to test and run linkprediction with these new changes.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 I get this error message when I run runLinkPrediction_ppi:

> Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/embiggen/runLinkPrediction_ppi.py", line 340, in <module>
    report = main(args)
  File "/Users/ravanv/PycharmProjects/embiggen/runLinkPrediction_ppi.py", line 293, in main
    args.num_walks, args.walk_length)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/cache_decorator/cache.py", line 61, in wrapped
    path = self._get_formatted_path(args, kwargs)
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/cache_decorator/cache.py", line 112, in _get_formatted_path
    {"params": params, "function_info": self.function_info})
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/dict_hash/dict_hash.py", line 37, in sha256
    return hashlib.sha256(_sanitize(d).encode('utf-8')).hexdigest()
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/dict_hash/dict_hash.py", line 23, in _sanitize
    return dumps(_convert(d))
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/dict_hash/dict_hash.py", line 12, in _convert
    return dict(map(_convert, data.items()))
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/dict_hash/dict_hash.py", line 18, in _convert
    return type(data)(map(_convert, data))
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/dict_hash/dict_hash.py", line 12, in _convert
    return dict(map(_convert, data.items()))
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/dict_hash/dict_hash.py", line 18, in _convert
    return type(data)(map(_convert, data))
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/dict_hash/dict_hash.py", line 19, in _convert
    raise ValueError("Type {} not currently supported.".format(type(data)))
ValueError: Type <class 'embiggen.csf_graph.csf_graph.CSFGraph'> not currently supported.

Do you know how to solve it? Thanks.

**Comment by LucaCappelletti94** [comment]
@vidarmehr on it!

**Comment by LucaCappelletti94** [comment]
Basically, we need to implement a function to hash uniquely the CSFGraph object, given the considered files. Do you think we could plan a short hackathon to refactor CSFGraph to support this? I will need a bit of help to understand the inner workings of the class.

**Comment by callahantiff** [comment]
> Basically, we need to implement a function to hash uniquely the CSFGraph object, given the considered files. Do you think we could plan a short hackathon to refactor CSFGraph to support this? I will need a bit of help to understand the inner workings of the class.

Ohh count me in. I just re-read a bunch of papers related to this and would LOVE to help!! What's your time frame for the hackathon?

**Comment by LucaCappelletti94** [comment]
@callahantiff would tomorrow one hour or two before the usual meeting work for you?

**Comment by pnrobinson** [comment]
Love to join the conversation but just a beginner. I thought that all of the objects within the class are "normal" (lists of strings and ints etc), and so it is not clear to me why we need a special hash function -- I'd love to understand better!

**Comment by callahantiff** [comment]
> @callahantiff would tomorrow one hour or two before the usual meeting work for you?

Tomorrow morning anytime after 8am MT works for me. @pnrobinson - what about you?

**Comment by LucaCappelletti94** [comment]
> Love to join the conversation but just a beginner. I thought that all of the objects within the class are "normal" (lists of strings and ints etc), and so it is not clear to me why we need a special hash function -- I'd love to understand better!

Basically the "normal" hash function from python is instance dependant: basically you get the same hash only within the same python instance. Between multiple python instances, the hash functions will take different values, for this reason, we will need to add a custom hash function to allow for non-instance-specific hashing since we want to be able to cache a function that accepts a CSFGraph object as a parameter.

**Comment by vidarmehr** [comment]
> > @callahantiff would tomorrow one hour or two before the usual meeting work for you?
> 
> Tomorrow morning anytime after 8am MT works for me. @pnrobinson - what about you?

Have you schedule for the meeting? If yes, then can you please include me in the meeting? Thanks.

**Comment by callahantiff** [comment]
> > > @callahantiff would tomorrow one hour or two before the usual meeting work for you?
> > 
> > 
> > Tomorrow morning anytime after 8am MT works for me. @pnrobinson - what about you?
> 
> Have you scheduled the meeting? If yes, then can you please include me in the meeting? Thanks.

I don't believe a meeting has been made for this, at least not that I am aware of.

**Comment by vidarmehr** [comment]
@callahantiff @LucaCappelletti94 Peter's schedule is full tomorrow from 10 am to 2 pm (ET). We can either meet at 2 pm (it is late for Luca), or we can meet at another time (maybe on Friday)? 
@pnrobinson Peter, would you please let us know when a good time is for you to have a small hackathon? Thanks.

**Comment by LucaCappelletti94** [comment]
> @callahantiff @LucaCappelletti94 Peter's schedule is full tomorrow from 10 am to 2 pm (ET). We can either meet at 2 pm (ET) (it is late for Luca), or we can meet at another time (maybe on Friday)?
> @pnrobinson Peter, would you please let us know when a good time is for you to have a small hackathon? Thanks.

For me 2 PM ET works, I'll get a take away for dinner. However, the task is not that daunting: the main issue is that complex objects may include attributes such as date times or ids that do not take part that much in describing the state of the Graph object but are more related to the specific instance. In our case, we only want to cache the data that have been loaded from a specific file, so basically we only need to select the parameters that interest us when building the hash.

Once we select the parameters, I will use the [sha256 method from dict_hash](https://github.com/LucaCappelletti94/dict_hash/blob/2e96a8a265a4cdb2f9ebb4da774f3934322bef7d/dict_hash/dict_hash.py#L33) to hash it in a deterministic manner.

**Comment by pnrobinson** [comment]
I cannot meet from 10-12PM but am free otherwise. If this does not work, please go ahead without me and fill me in later!

**Comment by LucaCappelletti94** [comment]
I have added the [stub consistent hash method](https://github.com/monarch-initiative/embiggen/blob/cbb51fb6041fa219b55ec89f1dd8d02290495091/embiggen/csf_graph/csf_graph.py#L511), now we only need to specify which parameters characterize uniquely an instance. 

I am currently struggling to understand what the CSFGraph is doing in the constructor, so I will wait for your expertise on that.

For me after 12PM EST, before the other meeting, should be okay!

**Comment by vidarmehr** [comment]
Ok. So, let's meet at 12 pm (ET). I can send a zoom invite from my personal account. But, it is not free after 40 minutes. @callahantiff Tiffany, can we use your zoom account for this meeting? Would you please send a zoom invite to us for today at 12 pm (ET)? Thanks.

**Comment by pnrobinson** [comment]
sorry, I messed up -- cannot join at 12 -- please go on without me and let me know!

**Comment by vidarmehr** [comment]
> Ok. So, let's meet at 12 pm (ET). I can send a zoom invite from my personal account. But, it is not free after 40 minutes. @callahantiff Tiffany, can we use your zoom account for this meeting? Would you please send a zoom invite to us for today at 12 pm (ET)? Thanks.

@callahantiff If your account is not free after 40 minutes, then please let me know that I ask Peter's assistant to schedule a webex meeting for us.

**Comment by callahantiff** [comment]
@vidarmehr - my account is free for more than 40 minutes, but I have a meeting at 12:30pm ET I will have to use it for (sorry!). So, I think it's best to use your meeting room this time.

**Comment by pnrobinson** [comment]
@vidarmehr is this issue still active or can it be closed?

**Comment by vidarmehr** [comment]
@pnrobinson It can be closed.
