### ISSUE TITLE
possibly a bug in SkipGramWord2Vec

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/embiggen#185]
per convo with Vida and Luca at the hackathon:

in `train()` [here at line 348](https://github.com/monarch-initiative/embiggen/blob/a23424e717d196fc69d2ff02dbd005e8c9e555a1/embiggen/word2vec.py#L348), we are iterating over `range(1, self.n_epochs + 1)`, but here in [line 321](https://github.com/monarch-initiative/embiggen/blob/a23424e717d196fc69d2ff02dbd005e8c9e555a1/embiggen/word2vec.py#L321) we are also iterating over `trange(1, self.n_epochs + 1):`

**Comment by pnrobinson** [comment]
I think we need to remove the iteration at line 348

**Comment by callahantiff** [comment]
> I think we need to remove the iteration at line 348

Agreed, that was my thought too.

**Comment by vidarmehr** [comment]
@julesjacobsen Hi Justin,
 Did you fix this issue and merged the branch to develop? I don't see it in develop?

**Comment by vidarmehr** [comment]
@julesjacobsen Oh, I just saw it. It was merged to master directly.

**Comment by justaddcoffee** [comment]
My apologies @vidarmehr - I merged to master instead of develop. I'll make another PR to merge into develop

**Comment by vidarmehr** [comment]
@justaddcoffee Not a problem at all, Justin! Thank you for fixing the issue.
