### ISSUE TITLE
question about gamma parameter calculation

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/embiggen#194]
@pnrobinson - we have a question about these lines, which contain two different uses of the gamma parameter: 

https://github.com/monarch-initiative/embiggen/blob/f8a847d56c73ec1a87d19f1a729baa2f03755f70/embiggen/hetnode2vec.py#L246 

https://github.com/monarch-initiative/embiggen/blob/f8a847d56c73ec1a87d19f1a729baa2f03755f70/embiggen/hetnode2vec.py#L318 

Notice the latter does not have parentheses around `count` and `num_types`, and is therefore a different calculation. Are these correct, and are they meant to be different? 

@LucaCappelletti94, Tomas and I discussed this for a while, and searched the literature a bit, but could not find a reference to clarify the correct use for gamma. 

Could you clarify?

**Comment by pnrobinson** [comment]
This is our new method and so there is no literature yet.
@vidarmehr  I think that only this is correct:
```
float(self.gamma) / (float(count) * num_types) 
```
and this looks like it is missing a parenthesis in the denominator
```
 own2prob[n] = float(self.gamma) / float(count) * num_types
```

**Comment by justaddcoffee** [comment]
thanks @pnrobinson - we'll assume the former is correct:
`float(self.gamma) / (float(count) * num_types)`
@vidarmehr could you let us know if we are mistaken?

**Comment by vidarmehr** [comment]
@justaddcoffee Yes, Justin!   Parenthesis were missing. We have not checked if this algorithm works or not. But, I think that is how probabilities should be calculated.

**Comment by justaddcoffee** [comment]
great thanks @vidarmehr !

**Comment by justaddcoffee** [comment]
@LucaCappelletti94 pushed a commit [here](e12684a850ade345763b8404e1d72d25c0ac3a81) to close this issue
