### ISSUE TITLE
Error in CBOW

### ISSUE THREAD

**Issue by LucaCappelletti94** [monarch-initiative/embiggen#197]
The currently implementation of CBOW has a [return statement **inside** the epoch loop](https://github.com/monarch-initiative/embiggen/blob/f8a847d56c73ec1a87d19f1a729baa2f03755f70/embiggen/word2vec.py#L678), hence it never did more that a single epoch.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Yes!! Thanks Luca. I was thinking that there must be a bug somewhere because I did not see any improvements in AUC score when I increased number of epochs.

**Comment by LucaCappelletti94** [comment]
I believe we should tackle this and the other errors I have mentioned on Gitter in refactoring of the word2vec methods.

**Comment by vidarmehr** [comment]
Yes! Let's solve the issues at the zoom meeting today.

**Comment by pnrobinson** [comment]
I think this was taken care of!
