### ISSUE TITLE
keyerror for subject or object starting with a colon eg ':BR', ':BS', ':CR'

### ISSUE THREAD

**Issue by realmarcin** [monarch-initiative/embiggen#205]
The leading colon is not a data bug. It just means there is no prefix for that CURIE

The leading colon is not a data bug. It just means there is no prefix for that CURIE. Its what we default to when we don't know what the prefix of a node id would be. So these CURIEs are valid and should work.

Here is some log output and stack trace -- suggesting this is failing on mapping embeddings to nodes:

SkipGram analysis
100%|██████████| 1/1 [24:30<00:00, 1470.19s/it]
 learning: 1473.876036643982 seconds
Finished ingesting 9806 lines (vectors) from embedded_graph.embedded

  File "runLinkPrediction_ppi.py", line 254, in <module>
    main(args)
  File "runLinkPrediction_ppi.py", line 248, in main
    linkpred(pos_train_graph, pos_valid_graph, pos_test_graph, neg_train_graph, neg_valid_graph, neg_test_graph)
  File "runLinkPrediction_ppi.py", line 172, in linkpred
    lp.prepare_edge_and_node_labels()
  File "/global/scratch/marcin/N2V/N2V/embiggen/link_prediction.py", line 146, in prepare_edge_and_node_labels
    node2vector_map=self.map_node_vector)
  File "/global/scratch/marcin/N2V/N2V/embiggen/link_prediction.py", line 412, in create_edge_embeddings
    emb1 = node2vector_map[node1]
KeyError: ':CR'

**Comment by pnrobinson** [comment]
@justaddcoffee is this still active?

**Comment by justaddcoffee** [comment]
@pnrobinson I can confirm that CURIEs with leading ':'s are handled correctly in `new_graph_representation` branch

**Comment by LucaCappelletti94** [comment]
If this is no longer active I can close the issue.

**Comment by LucaCappelletti94** [comment]
Closing this issue as deprecated in the new version of Embiggen. Please feel free to reopen as need be.
