### ISSUE TITLE
Given context window (3) is larger than at least one of the tensors in X (len=2)

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/embiggen#212]
We will need to adapt the extraction of word 2 vec sentences to skip sentences that are too short, otherwise we are likely to get this error a lot
```
 File "/home/peter/PycharmProjects/embiggen/embiggen/embedder/word2vec/word2vec.py", line 112, in fit
    super().fit(learning_rate=learning_rate,
  File "/home/peter/PycharmProjects/embiggen/embiggen/embedder/embedder.py", line 148, in fit
    raise ValueError((
ValueError: Given context window (3) is larger than at least one of the tensors in X (len=2)
```

**Comment by pnrobinson** [comment]
This is data from the Emails file
```
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor([], shape=(0,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor([23], shape=(1,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor([943], shape=(1,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor([38 32 71 13 24], shape=(5,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor([75 28  3 10  4  2  2  9  6  7 11], shape=(11,), dtype=int32)
```
Some of the sentences have zero length or 1 item.

**Comment by pnrobinson** [comment]
I tried this (text_encoder) but for some reason it is not working (i.e., it is still returning zero-length sentences) @callahantiff @deepakunni3  Is this the right way to do it in python?
```
cleaned_sentences =  [self.clean_text(sent) for sent in sentence_data]
return [sent for sent in cleaned_sentences if len(sentence_data) >= self.minlen]
```

**Comment by callahantiff** [comment]
@pnrobinson - how did you isolate this problem to the text_encoder workflow specifically? Does it seem like the output of that step is what is causing the error that you mentioned?

**Comment by pnrobinson** [comment]
I was trying to modify the text encoder to skip sentence shorter than self.minlen
(embedding_refactor branch). In the new Embedder class, we check whether there are sentences that are shorter than context_window, and that is where the error is coming from. I add this line
```
return [sent for sent in cleaned_sentences if len(sentence_data) >= self.minlen]
```
in an attempt to filter but apparently that does not work --

**Comment by callahantiff** [comment]
> I was trying to modify the text encoder to skip sentence shorter than self.minlen
> (embedding_refactor branch). In the new Embedder class, we check whether there are sentences that are shorter than context_window, and that is where the error is coming from. I add this line
> 
> ```
> return [sent for sent in cleaned_sentences if len(sentence_data) >= self.minlen]
> ```
> 
> in an attempt to filter but apparently that does not work --

Oh, I see!! OK. In that case, if we assume that the sentence_data is a nested list, then the code that are showing should work. I am guessing that it's not working because that class outputs a tensor object. Are you looking for a similar solution that works on a tensor object? I just want to make sure I am clear on what you are looking for :D.

**Comment by callahantiff** [comment]
One more question, can we assume that we know the window length and add it as an attribute to the text_encoder class? If so, I think I we can make an easy update in the pipeline prior to outputting tensors.

**Comment by pnrobinson** [comment]
In the branch, I added a minlen parameter to the text_encoder class, which probably makes sense anyway. But yes, in general we will know the window length in time to use the information for the text encoder.

**Comment by pnrobinson** [comment]
@callahantiff awesome thanks!
