### ISSUE TITLE
error when running test_graph_embedding

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/embiggen#216]
@LucaCappelletti94 Hi Luca,
I am receiving an error message when I run the tests in test_graph_embedding.py in new_graph_representation branch.
The error is:
```
Error
Traceback (most recent call last):
  File "/Users/ravanv/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/ravanv/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/ravanv/PycharmProjects/embiggen/tests/test_graph_embedding.py", line 104, in test_skipgram
    graphs["pos_train_edges"].walk(10, 80))
TypeError: EnsmallenGraph.walk() missing required positional argument: min_length

```
I successfully ran the code last week. Did you change anything in EnsmallenGraph? 
Thanks.

**Comment by LucaCappelletti94** [comment]
Hello Vida, yes EnsmallenGraph is quickly evolving to be able to introduce the features necessary to generate holdouts etc... and I still have to update accordingly the tests in Embiggen. We should be able to deploy a new version during the coming weekend if it's not blocking your work currently.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Oh, OK! No worries. Thanks, Luca:)
