### ISSUE TITLE
Update SonarCloud organization

### ISSUE THREAD

**Issue by LucaCappelletti94** [monarch-initiative/embiggen#219]
I believe we still need to update the SonarCloud organization to get its updated reports.

@pnrobinson could we have a short call do tackle that?

**Comment by pnrobinson** [comment]
@LucaCappelletti94 is this still active?

**Comment by LucaCappelletti94** [comment]
Yes, when do you have time to tackle this? Maybe tomorrow?

**Comment by pnrobinson** [comment]
Tomorrow 9AM or 1PM Eastern (=15h, 19h)?

**Comment by LucaCappelletti94** [comment]
I would go with the latter!

**Comment by pnrobinson** [comment]
OK, thanks, see you tomorrow 1PM/19h!
