### ISSUE TITLE
Error in splitting the edgelist

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/embiggen#230]
@LucaCappelletti94 Hi Luca, I am using Graph embedding using Skipgram jupyter notebook file to embed a heterogenous graph containing genes as nodes and two different edge types. I receive this error message when I run Split the graph into two edge partitions:

ValueError                                Traceback (most recent call last)
<ipython-input-25-e655ec9b15fd> in <module>
      1 assert graph > training
      2 assert graph > validation
----> 3 assert (training + validation).contains(graph)
      4 assert graph.contains(training + validation)
      5 assert not training.overlaps(validation)

ValueError: The two given graphs have overlapping edges, this is not supported since it's an undefined behaviour.

Can you please help me with this issue? Thanks.

**Comment by LucaCappelletti94** [comment]
Hello Vida, could you send me the report of the graph (and the graph files)?

**Comment by LucaCappelletti94** [comment]
I have identified the root of the issue (which is also relevant for a previous problem encountered by @justaddcoffee ). We have not defined the behaviour of the connected holdouts for multigraphs (graphs with multiple edge types).

We should have a call on the topic, to choose how to proceed.

**Comment by vidarmehr** [comment]
> Hello Vida, could you send me the report of the graph (and the graph files)?

Hi Luca,

{'selfloops_rate': '0.000014785572238609565',
 'bidirectional_rate': '1',
 'unique_node_types_number': '0',
 'degrees_mode': '1',
 'degrees_mean': '48.229260755883054',
 'degrees_max': '1399',
 'degrees_median': '15',
 'singleton_nodes': '0',
 'is_directed': 'false',
 'unique_edge_types_number': '2',
 'strongly_connected_components_number': '93',
 'nodes_number': '16828',
 'connected_components_number': '93',
 'edges_number': '811602',
 'density': '0.002866012642969043',
 'traps_rate': '0',
 'degrees_min': '1'}

**Comment by vidarmehr** [comment]
> I have identified the root of the issue (which is also relevant for a previous problem encountered by @justaddcoffee ). We have not defined the behaviour of the connected holdouts for multigraphs (graphs with multiple edge types).
> 
> We should have a call on the topic, to choose how to proceed.

Sure. Thanks. I will schedule a meeting with you and Peter. Does 10 am (ET) = 4 pm (Italy) work for you?

**Comment by pnrobinson** [comment]
I could do 10AM

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Luca, can we talk about this issue tomorrow? Thanks.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Sorry. I missed the meeting because of some issues with outlook on my machine. Did you discuss this problem?

**Comment by vidarmehr** [comment]
What about 11 am (ET) = 5pm Italy?

**Comment by LucaCappelletti94** [comment]
We are addressing this issue in this new holdout method: https://github.com/LucaCappelletti94/ensmallen_graph/issues/16

**Comment by vidarmehr** [comment]
I close this issue as we are addressing it in LucaCappelletti94/ensmallen_graph#16 and https://github.com/monarch-initiative/syntheticLethalityNetwork/issues/231
