### ISSUE TITLE
Graph embedding using Skipgram 

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/embiggen#233]
@LucaCappelletti94 @zommiommy 

Hi guys,
I am running Graph embedding using Skipgram on homogeneous version of the SLI graph and I am receiving this error message when I run block 4 of the notebook file: `training, validation = graph.connected_holdout(42, 0.8)`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-c23a7446339e> in <module>
----> 1 training, validation = graph.connected_holdout(42, 0.8)

TypeError: EnsmallenGraph.connected_holdout() takes at most 1 positional argument (2 given)

Maybe I am not using the correct branch or I should install ensmallen. Can you please let me know which branch I should use and if I need to install ensmallen? Thank you.

**Comment by justaddcoffee** [comment]
Hi Vida - 
try:
`training, validation = graph.connected_holdout(train_size=0.8, random_state=42)`
Does this work?

**Comment by vidarmehr** [comment]
@justaddcoffee Hi Justin. Thanks. No. I t does not work.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-b3776292db35> in <module>
----> 1 training, validation = graph.connected_holdout(train_size =0.8, random_state = 42)

TypeError: EnsmallenGraph.connected_holdout() missing required positional argument: train_percentage
I tried train_precentage instead of train_size, but it did not work either.

**Comment by LeoPompidou** [comment]
I think you can leave out the 42 and give just one argument (the 0.8)

**Comment by LucaCappelletti94** [comment]
Hello Vida, I just wanted to point out that the version of Ensmallen that is currently on Pypi does not support the type of holdout that we have been discussing for the SLI experiment and all these new algorithms are still very experimental.

I have completed the updated report on the SLI graphs and sent it to Giorgio for evaluation.
We are working on the develop branch of EnsmallenGraph if you were still interested in compiling and installing the latest version.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Hi Luca, Thanks. Leo and I want to have embedding of the homogeneous SLI graph. We will run embedding with new holdouts on the multigraph SLI after the implementation is complete.

**Comment by vidarmehr** [comment]
> I think you can leave out the 42 and give just one argument (the 0.8)
> `training, validation = graph.connected_holdout(0.8)`
Yes. Thanks, Leo.

**Comment by vidarmehr** [comment]
> I think you can leave out the 42 and give just one argument (the 0.8)
> `training, validation = graph.connected_holdout(0.8)`

Yes. Thanks, Leo.

**Comment by LucaCappelletti94** [comment]
> @LucaCappelletti94 Hi Luca, Thanks. Leo and I want to have embedding of the homogeneous SLI graph. We will run embedding with new holdouts on the multigraph SLI after the implementation is complete.

Ok, but the graph you currently have available does not include all the fixes that I have been resolving the past week and you would end-up with an embedding that is not useful for the prediction tasks that were proposed.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Thanks Luca. Well, we are hoping to get some initial results that Leo can use in his thesis. We may/may not use them in the paper though.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Luca, I have a workshop today (12 pm -3:30 pm ET) and I cannot attend the meeting today. If you have any questions, please send me an email or message on Gitter.

**Comment by vidarmehr** [comment]
@LucaCappelletti94 Luca, by the way, there are currently 15 branches in this repo. I think it is good to start merging them.
Maybe after you finish holdout implementation for the SLI graph, we can start merging the branches.

**Comment by LucaCappelletti94** [comment]
Done!

**Comment by LucaCappelletti94** [comment]
The holdout mechanism is entirely in Ensmallen.

**Comment by vidarmehr** [comment]
Thanks Luca. Did you delete 14 branches? I did not receive any notification for pull request, but it seems all branches are deleted, except the master.

**Comment by LucaCappelletti94** [comment]
Yes I have removed all the stale branches (all of the branches with updated features or not dead features that we just stopped developing).
