### ISSUE TITLE
Exporting EdgeTransformer Object

### ISSUE THREAD

**Issue by hrshdhgd** [monarch-initiative/embiggen#257]
We are looking a way to export the `EdgeTransformer` object (preferably serialized). Is there a method that already exists to do that?

What we are trying to do is this:

1. We trained an ML model (sklearn: Logistic Regression). 

2. We are trying to export a trained model to later import it and predict links on a graph. 

As far as we understand, we need to save off the `EdgeTransfomer` object that was fit in bullet 1 to proceed with bullet 2. 

Things we have tried:

1. When we try to `pickle.dump()` the `LinkPredictionTransformer` object, we get the following error:

```
E           _pickle.PicklingError: Can't pickle <function EdgeTransformer.<lambda> at 0x7fdbd1bd13a0>: attribute lookup EdgeTransformer.<lambda> on embiggen.transformers.edge_transformer failed
``` 

For context, [here's the code in NEAT ](https://github.com/Knowledge-Graph-Hub/NEAT/blob/8a7ba3612fbb6dd5c2d4a4fd645d4b3854b026c1/neat/link_prediction/model.py#L102) where we are trying to do this. 

Any suggestions/comments would be greatly appreciated!

cc: @justaddcoffee , @caufieldjh

**Comment by LucaCappelletti94** [comment]
Hello @hrshdhgd, breaking the issue in a few different points and premises:

- Why use a logistic regression instead of a GNN? It is readily available in Embiggen, and the Perceptron version of it is quite similar to a Logistic Regression in a few aspects if simplicity is the goal. This option does not use entirely the EdgeTransformer, as the edge encoding (if any) is done in the GPU. We can plan a call next week to look into this if needed.
- The EdgeTransformer model is not pickable because it uses Python lambdas for the conversion of the source and destination node embeddings into the edge embedding, which are not picklable, but I think I can refactor it to use class methods or any other similar solution. I will provide information on this soon enough.

**Comment by LucaCappelletti94** [comment]
This issue should be now resolved in the develop branch, please do let me know if it persists.

**Comment by hrshdhgd** [comment]
Thank you so much @LucaCappelletti94 ! I'm new to NEAT and the whole architecture and hence wasn't aware of the GNN availability in Embiggen. 

The issue of the lambdas does make sense and @caufieldjh did suspect that being the reason. 

Thanks again for the quick response. I'll install the develop branch locally, try it out some time this coming week and report back.

**Comment by justaddcoffee** [comment]
Thanks @LucaCappelletti94 ! 

> Why use a logistic regression instead of a GNN? It is readily available in Embiggen, and the Perceptron version of it is quite similar to a Logistic Regression in a few aspects if simplicity is the goal. This option does not use entirely the EdgeTransformer, as the edge encoding (if any) is done in the GPU. We can plan a call next week to look into this if needed.

We are using logistic regression just as a simple example of a classifier (basically we just need a working test example that exercises the whole process: graph -> embeddings -> train classifier -> apply classifier), but yes we'd love to implement support for GNNs in NEAT. 

Looks like we can now pickle edge transformers - thanks for the quick refactor! 

Maybe you could join our Monday daily hackathon on my zoom (10 am PT, 6 pm Italy) and we could discuss? It'd be great to get your input on all of this.

**Comment by LucaCappelletti94** [comment]
Hi @hrshdhgd, can you confirm that the pickling issue is fixed?

**Comment by hrshdhgd** [comment]
Hey @LucaCappelletti94 , I was going through the issue with @justaddcoffee and @caufieldjh today. It seemed like I still am seeing the same error in spite of upgrading embiggen and ensmallen to the latest dev versions.

**Comment by LucaCappelletti94** [comment]
Ok, could we do a short call where you show me the exact error? Do you have a Colab notebook where I can reproduce it?

**Comment by hrshdhgd** [comment]
I do not have a Collar notebook yet. I could create one and let you know so we could go through it together.

**Comment by hrshdhgd** [comment]
I installed the `develop` branch from embiggen and the pickling does seem to work! Thanks @LucaCappelletti94 !!
