### ISSUE TITLE
Negative samples (sampling) in edge prediction

### ISSUE THREAD

**Issue by deweihu96** [monarch-initiative/embiggen#303]
Hi!

Do you have a function to control negative samples in the training set for a binary link (edge) prediction? I couldn't find it myself.

Like, when predicting if a given link exists, we should do negative sampling to generate some links not in the training set, and sometimes we improve the ratio of negative samples to make it closer to the real-world distribution.

If there is no such function, could we put the negative samples in the training set ourselves? For example, edges with weights of zero.

Best regards.

**Comment by LucaCappelletti94** [comment]
All of the link prediction models as they are implemented in GRAPE come with the negative sampling built in, and it is designed to capture meaningful negatives for any provided graph. You can generate a custom negative graph for training other models using the negative_graph function. All of the models have also a parameter to define the rate of existing and non-existing edges.
