### ISSUE TITLE
Publish embiggen on PyPI

### ISSUE THREAD

**Issue by hannahblau** [monarch-initiative/embiggen#46]
Luca has plenty of experience with this, but for reference I located some relevant tutorials.

**How to publish on PyPI:**
[How to Publish an Open-Source Python Package to PyPI](https://realpython.com/pypi-publish-python-package/)
very thorough step-by-step guide

[How to write your own Python Package and publish it on PyPi](https://medium.com/@thucnc/how-to-publish-your-own-python-package-to-pypi-4318868210f9)

**How to organize a Python package:**
[Python Application Layouts: A Reference](https://realpython.com/python-application-layouts/)

[Python Packaging User Guide](https://packaging.python.org/)

**How to handle logging:**
[logging — Logging facility for Python](https://docs.python.org/3/library/logging.html)
part of standard library, doc includes links to tutorials

**Comment by pnrobinson** [comment]
@hannahblau @LucaCappelletti94 @deepakunni3 @justaddcoffee @vidarmehr  Should we publish this on PyPI in preparation for submission? We should have a 0.6 release next week that we could submit.

**Comment by deepakunni3** [comment]
@pnrobinson Absolutely 👍 

I would also recommend tracking changes between release via a ChangeLog.md and have Release Notes tied to each release. This helps in determining what changed and whats new.

**Comment by justaddcoffee** [comment]
> @hannahblau @LucaCappelletti94 @deepakunni3 @justaddcoffee @vidarmehr Should we publish this on PyPI in preparation for submission? We should have a 0.6 release next week that we could submit.

Sure, it'd be good to have this on PyPi when the paper is reviewed

**Comment by LucaCappelletti94** [comment]
Embiggen is now published on Embiggen (and we should publish the updated one in about 1 week, as the updated Ensmallen is finally getting stable)
