### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by callahantiff** [monarch-initiative/embiggen#85]
More housekeeping 😄 

@justaddcoffee - do you know if there is a consensus about how to handle within file logging? I have noticed that some files have it, some don't, and others have it, but it's current commented out.

How would you like me to proceed going forward?

**Comment by deepakunni3** [comment]
It would be great if all the print statements are moved to logging and at different levels (INFO, DEBUG, ERROR).

Also, another thing I would recommend is the formatting of logging. For example take a look here:

https://github.com/NCATS-Tangerine/kgx/blob/master/kgx/__init__.py#L50-L56

It tries to get the logging messages to be as descriptive, including where the logging is coming from.

**Comment by justaddcoffee** [comment]
Deepak's thoughts above seem very sensible: +1 for logging, -1 for print statements

Could just crib that `__init__.py`, or least the logging bit

**Comment by vidarmehr** [comment]
@callahantiff Shall we close this issue?

**Comment by callahantiff** [comment]
@vidarmehr - I think it might be worth bringing this up in the Thursday meeting. If everyone agrees on a plan (the suggestion made by @deepakunni3 sounds perfect), then we can make a plan on how to update the repo.

I will make a note in the N2V meeting agenda as a reminder to discuss this as I won't be at the meeting this week. Can you update me here after the meeting on what the group decided? Happy to help get the changes made later this week.

**Comment by vidarmehr** [comment]
@callahantiff Sure. Thanks.

**Comment by pnrobinson** [comment]
Where are we here -- should we implement the logging style above?

**Comment by vidarmehr** [comment]
We did not talk about this last week. What about talking about it in the Thursday meeting this week? Or if everyone agrees we should move all print statements to loggin?

**Comment by pnrobinson** [comment]
I thought the question was about what style of logging to do?

**Comment by justaddcoffee** [comment]
> I thought the question was about what style of logging to do?

For now, I'd vote we just agree to use `logging.debug()|info()|warning()|error()` calls instead of print statements. 

If we want to get fancy later, we could crib KGX's style that Deepak mentioned (basically just put an `__init__.py`, `config.py` and `config.yaml` in `xn2v` directory to make a logger we can use elsewhere in the code). Or we could do this now - glad to make a PR if we want to do this.

**Comment by deepakunni3** [comment]
@vidarmehr I see you are tidying up the codebase and replacing the print statements with logging as part of the `clean_up`. I'll assign this ticket to you then.

**Comment by vidarmehr** [comment]
> @vidarmehr I see you are tidying up the codebase and replacing the print statements with logging as part of the `clean_up`. I'll assign this ticket to you then.

Yes, Deepak. I will do it.

**Comment by vidarmehr** [comment]
print statements are converted to logging.
